services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/app
      - backend_node_modules:/app/node_modules
    command: node src/server.ts


volumes:
  backend_node_modules: